---
apiVersion: v1
kind: Pod
metadata:
  name: my-demo-pod
  labels: 
    app: mani
spec:
  containers:
    - name: my-nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
          protocol: TCP

    - name: my-alpine
      image: alpine
      args: 
        - sleep
        -  1d      

    