apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  activeDeadlineSeconds: 2
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
          protocol: TCP