apiVersion: v1
kind: Pod
metadta:
  name: my-pod
spec:
  activeDeadlineSeconds: 2
  containners:
    - name: my-nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP